import type { AllowPersonalUsage, UserFacingMessage } from 'android-management/types';

// The configuration applied to an enterprise.
export type Enterprise = {
  // The name of the enterprise which is generated by the server during creation, in the form enterprises/{enterpriseId}.
  name: string;

  // The types of Google Pub/Sub notifications enabled for the enterprise.
  enabledNotificationTypes: NotificationType[];

  // The topic which Pub/Sub notifications are published to, in the form projects/{project}/topics/{topic}. This field is only required if Pub/Sub notifications are enabled.
  pubsubTopic: string;

  // A color in RGB format that indicates the predominant color to display in the device management app UI. The color components are stored as follows: (red << 16) | (green << 8) | blue, where the value of each component is between 0 and 255, inclusive.
  primaryColor: number;

  // An image displayed as a logo during device provisioning. Supported types are: image/bmp, image/gif, image/x-ico, image/jpeg, image/png, image/webp, image/vnd.wap.wbmp, image/x-adobe-dng.
  logo: ExternalData;

  // The name of the enterprise displayed to users. This field has a maximum length of 100 characters.
  enterpriseDisplayName: string;

  // Terms and conditions that must be accepted when provisioning a device for this enterprise. A page of terms is generated for each value in this list.
  termsAndConditions: TermsAndConditions[];

  // Sign-in details of the enterprise.
  signinDetails: SigninDetail[];

  // The enterprise contact info of an EMM-managed enterprise.
  contactInfo: ContactInfo;

  // Settings for Google-provided user authentication.
  googleAuthenticationSettings: GoogleAuthenticationSettings;

  // Output only. The type of the enterprise.
  enterpriseType: EnterpriseType;

  // Output only. The type of a managed Google Play Accounts enterprise.
  managedGooglePlayAccountsEnterpriseType: ManagedGooglePlayAccountsEnterpriseType;

  // Output only. The type of managed Google domain.
  managedGoogleDomainType: ManagedGoogleDomainType;
};

// Types of notifications the device management server may send via Google Pub/Sub.
export enum NotificationType {
  // This value is ignored.
  NOTIFICATION_TYPE_UNSPECIFIED = 'NOTIFICATION_TYPE_UNSPECIFIED',

  // A notification sent when a device enrolls.
  ENROLLMENT = 'ENROLLMENT',

  // A notification sent when a device issues a status report.
  STATUS_REPORT = 'STATUS_REPORT',

  // A notification sent when a device command has completed.
  COMMAND = 'COMMAND',

  // A notification sent when device sends BatchUsageLogEvents.
  USAGE_LOGS = 'USAGE_LOGS',

  // A notification sent for an enterprise upgrade. An enterprise upgrade is a process that upgrades a managed Google Play Accounts enterprise to a managed Google domain.
  ENTERPRISE_UPGRADE = 'ENTERPRISE_UPGRADE',
}

// Data hosted at an external location. The data is to be downloaded by Android Device Policy and verified against the hash.
export type ExternalData = {
  // The absolute URL to the data, which must use either the http or https scheme. Android Device Policy doesn't provide any credentials in the GET request, so the URL must be publicly accessible. Including a long, random component in the URL may be used to prevent attackers from discovering the URL.
  url: string;

  // The base-64 encoded SHA-256 hash of the content hosted at url. If the content doesn't match this hash, Android Device Policy won't use the data.
  sha256Hash: string;
};

// A terms and conditions page to be accepted during provisioning.
export type TermsAndConditions = {
  // A short header which appears above the HTML content.
  header: UserFacingMessage;

  // A well-formatted HTML string. It will be parsed on the client with android.text.Html#fromHtml.
  content: UserFacingMessage;
};

// A resource containing sign in details for an enterprise. Use enterprises to manage SigninDetails for a given enterprise.
export type SigninDetail = {
  // Sign-in URL for authentication when device is provisioned with a sign-in enrollment token. The sign-in endpoint should finish authentication flow with a URL in the form of https://enterprise.google.com/android/enroll?et= for a successful login, or https://enterprise.google.com/android/enroll/invalid for a failed login.
  signinUrl: string;

  // An enterprise wide enrollment token used to trigger custom sign-in flow. This is a read-only field generated by the server.
  signinEnrollmentToken: string;

  // A JSON string whose UTF-8 representation can be used to generate a QR code to enroll a device with this enrollment token. To enroll a device using NFC, the NFC record must contain a serialized java.util.Properties representation of the properties in the JSON. This is a read-only field generated by the server.
  qrCode: string;

  /**
   * Controls whether personal usage is allowed on a device provisioned with this enrollment token.

   *  For company-owned devices:

   * Enabling personal usage allows the user to set up a work profile on the device.
    Disabling personal usage requires the user provision the device as a fully managed device.
    For personally-owned devices:

    * Enabling personal usage allows the user to set up a work profile on the device.
    * Disabling personal usage will prevent the device from provisioning. Personal usage cannot be disabled on personally-owned device.
   */
  allowPersonalUsage: AllowPersonalUsage;

  // Optional. Whether the sign-in URL should be used by default for the enterprise. The SigninDetail with defaultStatus set to SIGNIN_DETAIL_IS_DEFAULT is used for Google account enrollment method.
  defaultStatus: SigninDetailDefaultStatus;

  // An EMM-specified metadata to distinguish between instances of SigninDetail.
  tokenTag: string;
};

// Whether the sign-in URL should be used by default for the enterprise.
export enum SigninDetailDefaultStatus {
  // Equivalent to SIGNIN_DETAIL_IS_NOT_DEFAULT.
  SIGNIN_DETAIL_DEFAULT_STATUS_UNSPECIFIED = 'SIGNIN_DETAIL_DEFAULT_STATUS_UNSPECIFIED',

  // The sign-in URL will be used by default for the enterprise.
  SIGNIN_DETAIL_IS_DEFAULT = 'SIGNIN_DETAIL_IS_DEFAULT',

  // The sign-in URL will not be used by default for the enterprise.
  SIGNIN_DETAIL_IS_NOT_DEFAULT = 'SIGNIN_DETAIL_IS_NOT_DEFAULT',
}

// Contact details for managed Google Play enterprises.
export type ContactInfo = {
  // Email address for a point of contact, which will be used to send important announcements related to managed Google Play.
  contactEmail: string;

  // The name of the data protection officer.
  dataProtectionOfficerName: string;

  // The email of the data protection officer. The email is validated but not verified.
  dataProtectionOfficerEmail: string;

  // The phone number of the data protection officer The phone number is validated but not verified.
  dataProtectionOfficerPhone: string;

  // The name of the EU representative.
  euRepresentativeName: string;

  // The email of the EU representative. The email is validated but not verified.
  euRepresentativeEmail: string;

  // The phone number of the EU representative. The phone number is validated but not verified.
  euRepresentativePhone: string;
};

// Contains settings for Google-provided user authentication.
export type GoogleAuthenticationSettings = {
  // Output only. Whether users need to be authenticated by Google during the enrollment process. IT admin can specify if Google authentication is enabled for the enterprise for knowledge worker devices. This value can be set only via the Google Admin Console.
  googleAuthenticationRequired: GoogleAuthenticationRequired;
};

// Setting for whether Google authentication is required for this enterprise.
export enum GoogleAuthenticationRequired {
  // This value is not used.
  GOOGLE_AUTHENTICATION_REQUIRED_UNSPECIFIED = 'GOOGLE_AUTHENTICATION_REQUIRED_UNSPECIFIED',

  // 	Google authentication is not required.
  NOT_REQUIRED = 'NOT_REQUIRED',

  // User is required to be successfully authenticated by Google.
  REQUIRED = 'REQUIRED',
}

// The type of the enterprise.
export enum EnterpriseType {
  // This value is not used.
  ENTERPRISE_TYPE_UNSPECIFIED = 'ENTERPRISE_TYPE_UNSPECIFIED',

  // The enterprise belongs to a managed Google domain.
  MANAGED_GOOGLE_DOMAIN = 'MANAGED_GOOGLE_DOMAIN',

  // The enterprise is a managed Google Play Accounts enterprise.
  MANAGED_GOOGLE_PLAY_ACCOUNTS_ENTERPRISE = 'MANAGED_GOOGLE_PLAY_ACCOUNTS_ENTERPRISE',
}

// The type of a managed Google Play Accounts enterprise.
export enum ManagedGooglePlayAccountsEnterpriseType {
  // The managed Google Play Accounts enterprise type is not specified.
  MANAGED_GOOGLE_PLAY_ACCOUNTS_ENTERPRISE_TYPE_UNSPECIFIED = 'MANAGED_GOOGLE_PLAY_ACCOUNTS_ENTERPRISE_TYPE_UNSPECIFIED',

  // The enterprise is customer-managed
  CUSTOMER_MANAGED = 'CUSTOMER_MANAGED',

  // The enterprise is EMM-managed (deprecated).
  EMM_MANAGED = 'EMM_MANAGED',
}

// The type of managed Google domain.
export enum ManagedGoogleDomainType {
  // The managed Google domain type is not specified.
  MANAGED_GOOGLE_DOMAIN_TYPE_UNSPECIFIED = 'MANAGED_GOOGLE_DOMAIN_TYPE_UNSPECIFIED',

  // The managed Google domain is an email-verified team.
  TYPE_TEAM = 'TYPE_TEAM',

  // The managed Google domain is domain-verified.
  TYPE_DOMAIN = 'TYPE_DOMAIN',
}

export enum EnterpriseView {
  // The API will default to the BASIC view for the List method.
  ENTERPRISE_VIEW_UNSPECIFIED = 'ENTERPRISE_VIEW_UNSPECIFIED',

  // Includes name and enterpriseDisplayName fields.
  BASIC = 'BASIC',
}
