// A web token used to access the managed Google Play iframe.
export type WebToken = {
  // The name of the web token, which is generated by the server during creation in the form enterprises/{enterpriseId}/webTokens/{webTokenId}.
  name: string;

  // The token value which is used in the hosting page to generate the iframe with the embedded UI. This is a read-only field generated by the server.
  value: string;

  // The URL of the parent frame hosting the iframe with the embedded UI. To prevent XSS, the iframe may not be hosted at other URLs. The URL must use the https scheme.
  parentFrameUrl: string;

  /**
   * The features to enable. Use this if you want to control exactly which feature(s) will be activated; leave empty to allow all features.

    Restrictions / things to note:

    If no features are listed here, all features are enabled — this is the default behavior where you give access to all features to your admins.
    This must not contain any FEATURE_UNSPECIFIED values.
    Repeated values are ignored
   */
  enabledFeatures: IframeFeature[];
};

// The feature available via an iframe that this WebToken will give access to. https://developers.google.com/android/management/reference/rest/v1/enterprises.webTokens#iframefeature
export enum IframeFeature {
  // Unspecified feature.
  FEATURE_UNSPECIFIED = 'FEATURE_UNSPECIFIED',

  PLAY_SEARCH = 'PLAY_SEARCH',
  PRIVATE_APPS = 'PRIVATE_APPS',
  WEB_APPS = 'WEB_APPS',
  STORE_BUILDER = 'STORE_BUILDER',
  MANAGED_CONFIGURATIONS = 'MANAGED_CONFIGURATIONS',
  ZERO_TOUCH_CUSTOMER_MANAGEMENT = 'ZERO_TOUCH_CUSTOMER_MANAGEMENT',
}
